/**
 * E2E Test Helpers
 * Shared utilities for all E2E tests
 *
 * Note: The timer view now uses a radial dial UI by default
 * Key selectors for radial mode:
 * - Number input: .dial-number[data-num="X"] (generated by RadialDial component)
 * - Clear button: #radial-clear-btn
 * - Timestamp button: #radial-time-btn
 * - Bib display: #radial-bib-value
 * - Timing points: .radial-point-btn[data-point="S|F"]
 * - Run selector: #radial-run-selector .radial-run-btn[data-run="X"]
 * - Confirmation: #radial-confirmation-overlay.show
 */

/**
 * Setup page with onboarding bypassed and clean state
 * Call this in beforeEach to ensure consistent test state
 * Note: Normal mode (simple=false) is now the default with radial dial UI
 */
export async function setupPage(page) {
  // Set localStorage to bypass onboarding before navigating
  await page.addInitScript(() => {
    localStorage.setItem('skiTimerHasCompletedOnboarding', 'true');
    // Set default settings for consistent test state
    // Keys must match the store's DEFAULT_SETTINGS: auto, haptic, sound, sync, gps, simple, photoCapture, syncPhotos
    localStorage.setItem('skiTimerSettings', JSON.stringify({
      auto: true,
      haptic: true,
      sound: false,
      sync: false,
      syncPhotos: false,
      gps: false,
      simple: false,  // Normal mode is default
      photoCapture: false
    }));
    localStorage.setItem('skiTimerLang', 'de');
  });

  await page.goto('/');
  // Wait for app to be ready (radial dial is rendered)
  await page.waitForSelector('#radial-time-hm', { timeout: 5000 });
}

/**
 * @deprecated Use setupPage() instead - normal mode is now the default
 */
export async function setupPageFullMode(page) {
  return setupPage(page);
}

/**
 * Setup page with English language
 */
export async function setupPageEnglish(page) {
  await page.addInitScript(() => {
    localStorage.setItem('skiTimerHasCompletedOnboarding', 'true');
    // Keys must match the store's DEFAULT_SETTINGS
    localStorage.setItem('skiTimerSettings', JSON.stringify({
      auto: true,
      haptic: true,
      sound: false,
      sync: false,
      syncPhotos: false,
      gps: false,
      simple: false,  // Normal mode is default
      photoCapture: false
    }));
    localStorage.setItem('skiTimerLang', 'en');
  });

  await page.goto('/');
  await page.waitForSelector('#radial-time-hm', { timeout: 5000 });
}

/**
 * Setup page with sync enabled
 */
export async function setupPageWithSync(page, raceId = 'TEST-RACE') {
  await page.addInitScript((raceId) => {
    localStorage.setItem('skiTimerHasCompletedOnboarding', 'true');
    // Keys must match the store's DEFAULT_SETTINGS
    localStorage.setItem('skiTimerSettings', JSON.stringify({
      auto: true,
      haptic: true,
      sound: false,
      sync: true,  // Sync enabled
      syncPhotos: false,
      gps: false,
      simple: false,  // Full mode for sync testing
      photoCapture: false
    }));
    localStorage.setItem('skiTimerLang', 'de');
    localStorage.setItem('skiTimerRaceId', raceId);
  }, raceId);

  await page.goto('/');
  await page.waitForSelector('#radial-time-hm', { timeout: 5000 });
}

/**
 * Clear all app data
 */
export async function clearAppData(page) {
  await page.evaluate(() => {
    localStorage.removeItem('skiTimerEntries');
    localStorage.removeItem('skiTimerSettings');
    localStorage.removeItem('skiTimerRaceId');
    localStorage.removeItem('skiTimerDeviceId');
    localStorage.removeItem('skiTimerAuthToken');
    localStorage.removeItem('skiTimerRecentRaces');
    // Keep onboarding bypassed
    localStorage.setItem('skiTimerHasCompletedOnboarding', 'true');
  });
}

/**
 * Click a toggle by clicking its label wrapper
 */
export async function clickToggle(page, toggleSelector) {
  await page.locator(`label:has(${toggleSelector})`).click();
}

/**
 * Check if toggle is on
 */
export async function isToggleOn(page, toggleSelector) {
  return await page.locator(toggleSelector).isChecked();
}

/**
 * Navigate to a specific view
 */
export async function navigateTo(page, view) {
  // data-view values match view names directly: timer, results, settings
  await page.click(`[data-view="${view}"]`);
}

/**
 * Record a timestamp with optional bib number
 * Uses radial dial UI selectors
 */
export async function recordTimestamp(page, bib = null) {
  if (bib) {
    // Clear current bib first
    await page.click('#radial-clear-btn');
    // Enter new bib via dial numbers
    for (const digit of bib.toString()) {
      await page.click(`.dial-number[data-num="${digit}"]`);
    }
  }
  await page.click('#radial-time-btn');
  // Wait for confirmation overlay
  await page.waitForSelector('#radial-confirmation-overlay.show', { timeout: 2000 });
}

/**
 * Wait for any toast notifications to disappear
 * Useful when toast intercepts pointer events on underlying buttons
 */
export async function waitForToastToHide(page) {
  await page.waitForFunction(() => {
    const toast = document.querySelector('.toast');
    return !toast || !toast.closest('#toast-container');
  }, { timeout: 5000 }).catch(() => {
    // Toast might not exist - continue
  });
  // Small buffer for animation
  await page.waitForTimeout(100);
}

/**
 * Wait for confirmation overlay to disappear
 * Increased timeout for slower CI environments (especially mobile-safari)
 * Uses radial confirmation overlay selector
 */
export async function waitForConfirmationToHide(page) {
  // First wait for it to appear (if not already visible)
  try {
    await page.waitForSelector('#radial-confirmation-overlay.show', { timeout: 2000 });
  } catch {
    // Overlay might have already hidden or never appeared - continue
  }
  // Then wait for it to hide
  await page.waitForSelector('#radial-confirmation-overlay.show', { state: 'hidden', timeout: 5000 });
}

/**
 * Enter bib number via radial dial
 * Uses dial numbers generated by RadialDial component
 */
export async function enterBib(page, bib) {
  // Wait for dial numbers to be rendered (Safari needs extra time in landscape)
  await page.waitForSelector('.dial-number[data-num="0"]', { state: 'visible', timeout: 5000 });
  // Wait for clear button to be ready (not covered by overlay)
  await page.waitForSelector('#radial-clear-btn', { state: 'visible' });
  await page.click('#radial-clear-btn');
  for (const digit of bib.toString().padStart(3, '0')) {
    await page.click(`.dial-number[data-num="${digit}"]`);
  }
}
